services:
  spo-audit:
    build: .
    image: rtb-spo-audit
    container_name: rtb-spo-audit
    ports:
      - "127.0.0.1:8501:8501"
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
