services:
  spo-audit:
    build: .
    image: rtb-spo-audit
    container_name: rtb-spo-audit
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 500M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spo.rule=Host(`spo.alanwegrzyn.com`)"
      - "traefik.http.routers.spo.entrypoints=websecure"
      - "traefik.http.routers.spo.tls.certresolver=mytlschallenge"
      - "traefik.http.services.spo.loadbalancer.server.port=8501"
